name: test-expression

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: echo ${{ 1 == 1 }}
      - name: Run command
        run: echo ${{ 1 == 3 }}
      - name: Run command
        run: echo ${{'Hello world'}}
        
      - name: if 'fullstring' contains 'string'
        run: echo "Contains check:${{ contains('fullstring', 'string') }}"

      - name: if 'fullstring' starts with 'fulstring'
        run: echo "Starts with check:${{ startsWith('fullstring', 'fulstring') }}"

      - name: if 'fullstring' ends with 'string'
        run: echo "Ends with check:${{ endsWith('fullstring', 'string') }}"
        
  test2:
    runs-on: ubuntu-latest
    steps:
       
      - name: if 'fullstring' contains 'string'
        if: ${{ contains('fullstring', 'string') }}
        run: echo "Contains check:${{ contains('fullstring', 'string') }}"

      - name: if 'fullstring' starts with 'fulstring'
        if: ${{ startsWith('fullstring', 'string') }}
        run: echo "Starts with check:${{ startsWith('fullstring', 'fulstring') }}"

      - name: if 'fullstring' ends with 'string'
        if: ${{ startsWith('fullstring', 'string') }}
        run: echo "Ends with check:${{ endsWith('fullstring', 'string') }}"

